states:
  - name: "pd"
    type: "pd"
    pd:
      q_des: [
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0,
        0.2, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.2, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0
      ]
      kp: 240.0
      kd: 5.0
