include:
  - config/common.yaml
  - config/policies.yaml
  - config/states/passive.yaml
  - config/states/pd.yaml
  - config/states/stand/policy.yaml
  - config/states/stand/state.yaml
  - config/states/walk/policy.yaml
  - config/states/walk/state.yaml
  - config/states/run/policy.yaml
  - config/states/run/state.yaml
  - config/fsm.yaml
